### ISSUE TITLE
Build esptool2 for Linux32, Linux64, OSX

### ISSUE THREAD

**Issue by digistump** [digistump/OakCore#11]
Builds with gcc, no external dependencies - if anyone has a chance to build on these platforms and upload it would be much appreciated.

Clone or download https://github.com/raburton/esptool2
"make"

Upload resulting binary here.

**Comment by CompyENG** [comment]
As requested, for Linux64 :smile: [esptool2.zip](https://github.com/digistump/OakCore/files/95252/esptool2.zip)

**Comment by digistump** [comment]
thanks again @TrueJournals

**Comment by DarkLotus** [comment]
[esptool2.zip](https://github.com/digistump/OakCore/files/95257/esptool2.zip)
Compiled on osx10.10

**Comment by DarkLotus** [comment]
[esptool2-linux32.zip](https://github.com/digistump/OakCore/files/95523/esptool2-linux32.zip)
linux 32 version.

**Comment by digistump** [comment]
Thank you both - this was a huge help in getting the first release out tonight!
