### ISSUE TITLE
Make OakCLI tool block until upload is complete

### ISSUE THREAD

**Issue by digistump** [digistump/OakCore#15]
Particle doesn't provide upload progress when doing an OTA flash, but we can see what the upload to the device is complete and knowing that would make it much easier to know what is going on.

**Comment by jhitze** [comment]
Should this be in https://github.com/digistump/OakCLI ?

**Comment by digistump** [comment]
Technically yes - but I prefer to use this issue tracker for the whole project, at least for my random "to-do list" thoughts

**Comment by thunderace** [comment]
Done : have a look [here](https://github.com/thunderace/OakCLI). I made a pull request

**Comment by digistump** [comment]
Thanks following up in that pull!
