### ISSUE TITLE
Oak WIFI scanning issue

### ISSUE THREAD

**Issue by michaellzc** [digistump/OakCore#27]
When I try to setup the oak, I can't get a full list of the avaiable network around my place, only a part of it.

**Comment by DarkLotus** [comment]
Yes their is an internal limitation to only display the first 10 Access
points.

If your AP is not shown, you can enter the SSID and password manually via
the SoftAP config.html.

**Comment by digistump** [comment]
Yep, it is limited to 10 APs, we may expand this in the future - DarkLotus is correct - closing this issue.
