### ISSUE TITLE
SoftAP Config App URL Invalid

### ISSUE THREAD

**Issue by dale3h** [digistump/OakCore#48]
The URL for the SoftAP Config App is missing a lowercase "L" at the end of it, resulting in a 404 error.

Wiki page: http://digistump.com/wiki/oak/tutorials/arduino
Invalid URL: http://rawgit.com/digistump/OakSoftAP/master/config.htm (missing "l" at the end)

I tried to register for an account on the wiki so that I can fix this typo, but have been unable to do so. How do I go about doing this?

**Comment by digistump** [comment]
Fixed - thanks - looks like someone edited the wiki to make that link in a code block, but deleted the last letter.

Register for the wiki by registering for the forums - looks like a wiki update wiped that message out on the login screen.
