### ISSUE TITLE
Board manager not showing Oak 0.9.4 (it shows 0.9.3 as the latest)

### ISSUE THREAD

**Issue by dale3h** [digistump/OakCore#49]
As the title says, the Arduino Board Manager is not showing 0.9.4 as the latest available package. I checked the JSON file in my browser and there appears to be no references to 0.9.4 anywhere.

**Comment by digistump** [comment]
Opps! I pushed it to github as I called it a night, looks like it failed to push, re-pushed now and double checked and it all looks good - sorry for that!
