### ISSUE TITLE
Tone implementation

### ISSUE THREAD

**Issue by jackygurui** [digistump/OakCore#65]
Hi @digistump just wondering if there will be an implementation of https://github.com/digistump/OakCore/blob/master/cores/oak/Tone.cpp any time soon?

**Comment by digistump** [comment]
Yes - likely soon - the main ESP8266 project has recently added an implementation, which you can use (https://github.com/esp8266/Arduino/blob/master/cores/esp8266/Tone.cpp) but there are some reports of major bugs with it (that you can't turn it off, can't change the tone) - so we'll wait for it to be a bit more stable before we merge it - leaving this open though so I don't forget

**Comment by micahwedemeyer** [comment]
👍  for tone support. I'm running a buzzer and playing some basic sound on it via PWM, but it would be great to be able to use tone.

**Comment by digistump** [comment]
The next release will have this integrated - in the mean time you can replace your Tone.cpp for the Oak with the latest one and it "should" work: https://github.com/digistump/OakCore/blob/master/cores/oak/Tone.cpp

**Comment by ekettenburg** [comment]
in 1.0.6
